### ISSUE TITLE
Verification fragment

### ISSUE THREAD

**Issue by TCSS450-Group2** [benny08y/TCSS450-ChatApp#4]
_From @enochchan2010 on October 22, 2018 21:52_

- o Upon registration attempt, do not log the user in, display a page informing the user of the verification process

_Copied from original issue: TCSS450-Group2/final-project#4_

**Comment by TCSS450-Group2** [comment]
_From @enochchan2010 on October 22, 2018 21:53_

dependent on #3

**Comment by enochchan2010** [comment]
Lab 3 verification email
